from django.conf import settings
from django.db import models
from pgvector.django import HnswIndex, VectorField

from apps.core.models import TimestampedModel


class Repository(TimestampedModel):
    """A codebase registered for review."""

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="repositories",
    )
    language = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text="Primary programming language of the repository.",
    )
    default_branch = models.CharField(max_length=100, default="main")

    class Meta:
        verbose_name_plural = "repositories"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.name


class CodeFile(TimestampedModel):
    """Snapshot of a single file submitted for review."""

    repository = models.ForeignKey(
        Repository, on_delete=models.CASCADE, related_name="files"
    )
    path = models.CharField(max_length=500, help_text="Relative file path, e.g. src/main.py")
    content = models.TextField(help_text="Full file content at time of review.")
    language = models.CharField(max_length=50, blank=True, default="")
    sha = models.CharField(max_length=64, blank=True, default="", help_text="Git blob SHA.")
    line_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["path"]
        unique_together = [("repository", "path", "sha")]

    def save(self, *args, **kwargs):
        if self.content:
            self.line_count = self.content.count("\n") + 1
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.path


class ReviewSession(TimestampedModel):
    """A collaborative review session — the main workspace where reviewers
    annotate code files in real-time via WebSocket connections."""

    class Status(models.TextChoices):
        OPEN = "open", "Open"
        IN_PROGRESS = "in_progress", "In Progress"
        COMPLETED = "completed", "Completed"
        ARCHIVED = "archived", "Archived"

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    repository = models.ForeignKey(
        Repository, on_delete=models.CASCADE, related_name="sessions"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="authored_sessions",
    )
    reviewers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="assigned_sessions",
        blank=True,
    )
    files = models.ManyToManyField(CodeFile, related_name="sessions", blank=True)
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.OPEN, db_index=True
    )
    branch = models.CharField(max_length=100, blank=True, default="main")

    def __str__(self) -> str:
        return f"{self.title} ({self.status})"


class Annotation(TimestampedModel):
    """Anchored to a specific line range in a file. Each annotation
    can have a thread of comments underneath it."""

    session = models.ForeignKey(
        ReviewSession, on_delete=models.CASCADE, related_name="annotations"
    )
    file = models.ForeignKey(
        CodeFile, on_delete=models.CASCADE, related_name="annotations"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="annotations"
    )
    start_line = models.PositiveIntegerField()
    end_line = models.PositiveIntegerField()
    resolved = models.BooleanField(default=False)

    class Meta:
        ordering = ["file", "start_line"]

    def __str__(self) -> str:
        return f"Annotation on {self.file.path}:{self.start_line}-{self.end_line}"


class Comment(TimestampedModel):
    """Single comment within an annotation thread. Can be human or AI-generated."""

    annotation = models.ForeignKey(
        Annotation, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    body = models.TextField()
    is_ai_generated = models.BooleanField(
        default=False,
        help_text="True if this was generated by the AI suggestion engine.",
    )

    class Meta:
        ordering = ["created_at"]

    def __str__(self) -> str:
        prefix = "[AI] " if self.is_ai_generated else ""
        return f"{prefix}{self.author.username}: {self.body[:60]}"


class ReviewChunk(TimestampedModel):
    """Stores embedded chunks of code/review content for the RAG pipeline.

    Using text-embedding-3-small (1536 dimensions) with pgvector HNSW index
    for approximate nearest neighbor search. Tried IVFFlat first but HNSW
    gave better recall at our data sizes without needing to tune nlist.

    Each chunk is ~400 tokens with 30-line overlap — see chunk_text()
    in core/utils.py for the splitting logic.
    """

    repository = models.ForeignKey(
        Repository, on_delete=models.CASCADE, related_name="chunks"
    )
    source_file = models.CharField(max_length=500, help_text="Original file path.")
    content = models.TextField(help_text="The text chunk from the review/code.")
    embedding = VectorField(
        dimensions=1536,
        help_text="text-embedding-3-small vector (1536d).",
    )
    metadata = models.JSONField(
        default=dict,
        help_text="Additional context: review session ID, author, language, etc.",
    )
    chunk_type = models.CharField(
        max_length=20,
        choices=[
            ("code", "Code"),
            ("review", "Review Comment"),
            ("diff", "Diff Hunk"),
        ],
        default="code",
        db_index=True,
    )

    class Meta:
        indexes = [
            HnswIndex(
                name="reviewchunk_embedding_idx",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
        ]

    def __str__(self) -> str:
        return f"Chunk({self.chunk_type}): {self.source_file}"


class AISuggestion(TimestampedModel):
    """AI-generated inline suggestion from the RAG pipeline.

    The confidence score comes from the LLM's self-assessment —
    not perfect but gives us something to rank/filter on.
    """

    # TODO: add a feedback field so reviewers can rate suggestion quality
    # would help with fine-tuning the prompt over time

    session = models.ForeignKey(
        ReviewSession, on_delete=models.CASCADE, related_name="suggestions"
    )
    file = models.ForeignKey(
        CodeFile, on_delete=models.CASCADE, related_name="suggestions"
    )
    start_line = models.PositiveIntegerField()
    end_line = models.PositiveIntegerField()
    suggestion_text = models.TextField(
        help_text="The AI-generated suggestion for this code region."
    )
    confidence = models.FloatField(
        default=0.0,
        help_text="Confidence score (0.0 - 1.0) from the RAG pipeline.",
    )
    context_chunks = models.ManyToManyField(
        ReviewChunk,
        blank=True,
        related_name="suggestions",
        help_text="The retrieved chunks that informed this suggestion.",
    )
    accepted = models.BooleanField(
        default=False,
        help_text="Whether the reviewer accepted the suggestion.",
    )

    class Meta:
        ordering = ["file", "start_line"]

    def __str__(self) -> str:
        status = "accepted" if self.accepted else "pending"
        return f"Suggestion({status}): {self.file.path}:{self.start_line}"
